# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d6018df9166a8b17f2fd6f71e2f400761f0ddc576732fa7e2e737797d527356a74f0cb45a7c760bf8e1cbbded04d0d0cee21e5bc35c9d212a65de78832162d
  pubnub_subscribe_key: pub-c-c15a9148-5866-46ba-81b8-4920dee0de63
  pubnub_publish_key: sub-c-10b0e09a-8ec5-11e6-a8c4-0619f8945a4f
  pubnub_secret_key: sec-c-NzUwODM5NGEtYzI1Mi00NmUwLWFhMTEtMTEzYmY5NjM2ZDlm
test:
  secret_key_base: 3ce8f5277970b90f3d7d780e3a1f4d7d60343dcf33c4aa869547e82218540e08763229cac2d054087ecbd740e6524e2e524fd7b584536d7cf09578334f52b0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
